import Footer from '../components/Footer'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Menu = () => {
  return (
    <>
      <p>Menu</p>
      <style jsx>{`
        p {
          margin: 0.5rem 0;
          text-align: center;
        }
      `}</style>
    </>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Microfront - Footer</title>
        <meta name='' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Footer menu={<Menu />} />
      </main>
    </div>
  )
}

export default Home
